import HERMIT.API
script :: Shell ()
script = do
  eval "flatten-module"
  eval "binding-of 'qsort"
  eval "static-arg"
  eval "{"
  eval "    binding-of 'qsort'"
  eval "    fix-intro"
  eval "    def-rhs"
  eval "    split-1-beta qsort [|absR|] [|repR|] ; assume"
  eval "    rhs-of 'worker"
  eval "    repeat (any-call (unfold ['.,'fix,'g,'repR,'absR]))"
  eval "    simplify"
  eval "    one-td (case-float-arg-lemma repHstrict) ; assume"
  eval "    innermost let-float"
  eval "    any-td (unfold-rule \"repH ++\") ; assume"
  eval "    any-call (unfold-rule repH-absH-fusion) ; assume"
  eval "    unshadow"
  eval "    any-td (inline 'ds1)"
  eval "    simplify"
  eval "    alpha-let [worker]"
  eval "    repeat (any-call (unfold-rules [\"repH (:)\",\"repH []\"]))"
  eval "    assume ; assume"
  eval "}"
  eval "repeat (any-call (unfold ['.,'absR, 'absH]))"
  eval "innermost let-float"
  eval "bash"

